const menu = {
    list() {
        return [
    {
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"教材类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryJiaocaizhuanzhu"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"工作类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryJiaoxuegongzuo"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"课题类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryKetixinxi"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"论文类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryLuenwen"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"公告类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryNews"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"荣誉类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryZhiyepeixun"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"专利类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryZhuanlixinxi"
                    }
                ],
                "menu":"基础数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"教材信息管理",
                        "menuJump":"列表",
                        "tableName":"jiaocaizhuanzhu"
                    }
                ],
                "menu":"教材信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "报表",
                            "删除"
                        ],
                        "menu":"教学工作管理",
                        "menuJump":"列表",
                        "tableName":"jiaoxuegongzuo"
                    }
                ],
                "menu":"教学工作管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"课题信息管理",
                        "menuJump":"列表",
                        "tableName":"ketixinxi"
                    }
                ],
                "menu":"课题信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"论文信息管理",
                        "menuJump":"列表",
                        "tableName":"luenwen"
                    }
                ],
                "menu":"论文信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公告信息管理",
                        "menuJump":"列表",
                        "tableName":"news"
                    }
                ],
                "menu":"公告信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "报表",
                            "删除"
                        ],
                        "menu":"教师管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"教师管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"荣誉信息管理",
                        "menuJump":"列表",
                        "tableName":"zhiyepeixun"
                    }
                ],
                "menu":"荣誉信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"专利信息管理",
                        "menuJump":"列表",
                        "tableName":"zhuanlixinxi"
                    }
                ],
                "menu":"专利信息管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    },
	{
	    "backMenu":[
	        {
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改",
	                        "删除"
	                    ],
	                    "menu":"教材信息管理",
	                    "menuJump":"列表",
	                    "tableName":"jiaocaizhuanzhu"
	                }
	            ],
	            "menu":"教材信息管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改",
	                        "删除"
	                    ],
	                    "menu":"教学工作管理",
	                    "menuJump":"列表",
	                    "tableName":"jiaoxuegongzuo"
	                }
	            ],
	            "menu":"教学工作管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改",
	                        "删除"
	                    ],
	                    "menu":"课题信息管理",
	                    "menuJump":"列表",
	                    "tableName":"ketixinxi"
	                }
	            ],
	            "menu":"课题信息管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改",
	                        "删除"
	                    ],
	                    "menu":"论文信息管理",
	                    "menuJump":"列表",
	                    "tableName":"luenwen"
	                }
	            ],
	            "menu":"论文信息管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"公告信息管理",
	                    "menuJump":"列表",
	                    "tableName":"news"
	                }
	            ],
	            "menu":"公告信息管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改",
	                        "删除"
	                    ],
	                    "menu":"荣誉信息管理",
	                    "menuJump":"列表",
	                    "tableName":"zhiyepeixun"
	                }
	            ],
	            "menu":"荣誉信息管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改",
	                        "删除"
	                    ],
	                    "menu":"专利信息管理",
	                    "menuJump":"列表",
	                    "tableName":"zhuanlixinxi"
	                }
	            ],
	            "menu":"专利信息管理"
	        }
	    ],
	    "frontMenu":[],
	    "hasBackLogin":"是",
	    "hasBackRegister":"否",
	    "hasFrontLogin":"否",
	    "hasFrontRegister":"否",
	    "roleName":"教师",
	    "tableName":"yonghu"
	}
]
    }
}
export default menu;
